apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1       
  #     maxUnavailable: 0 
      
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: __IMAGE__
        ports:
        - containerPort: 5004 
        env:
        - name: DB_HOST
          value: "__DB_HOST__" 
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "__DB_PASSWORD__" 
        - name: DB_NAME
          value: "__DB_NAME__"
          
        # resources:
        #   requests:
        #     cpu: "50m"      
        #     memory: "128Mi" 
        #   limits:
        #     cpu: "500m"     
        #     memory: "512Mi"  

        # readinessProbe:
        #   httpGet:
        #     path: /health/ready
        #     port: 5004
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /health/live
        #     port: 5004
        #   initialDelaySeconds: 15
        #   periodSeconds: 15