apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1       
  #     maxUnavailable: 0 
      
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: __IMAGE__
        ports:
        - containerPort: 5002 
        env:
        - name: DB_HOST
          value: "__DB_HOST__" 
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "__DB_PASSWORD__" 
        - name: DB_NAME
          value: "__DB_NAME__" 
        - name: USER_SERVICE_URL
          value: "http://user-service" 
          
        # resources:
        #   requests:
        #     cpu: "50m"      
        #     memory: "128Mi" 
        #   limits:
        #     cpu: "500m"     
        #     memory: "512Mi"    

        # readinessProbe:
        #   httpGet:
        #     path: /health/ready
        #     port: 5002
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /health/live
        #     port: 5002
        #   initialDelaySeconds: 15
        #   periodSeconds: 15